### ISSUE TITLE
The commands do not work.

### ISSUE THREAD

**Issue by Krot666** [SovCoinX/SovCoin#1]
I ran these commands one at a time:
./autogen.sh
./configure
make
But the **make** command does not work!
![screenshot_2](https://user-images.githubusercontent.com/33595988/43033744-778c44f6-8cf9-11e8-9eae-505554e07c2d.png)

**Comment by AnarchistsPrime** [comment]
(not an issue,run)
make clean
 ./autogen.sh && ./configure --with-incompatible-bdb && make

**Comment by Krot666** [comment]
Does not work((

![screenshot_2](https://user-images.githubusercontent.com/33595988/43042274-7a4803ba-8da3-11e8-90dc-98cb59f8a881.png)

**Comment by AnarchistsPrime** [comment]
cd SovCoin/src/secp256k1/
./autogen.sh
./configure
make
cd..
cd..

Then compile again.

**Comment by Krot666** [comment]
Nothing happens ((
![2](https://user-images.githubusercontent.com/33595988/43059541-18797f9a-8e77-11e8-900d-09620c9eea88.png)
![3](https://user-images.githubusercontent.com/33595988/43059542-189f242a-8e77-11e8-85b7-1f3abe8a8535.png)

**Comment by SovCoinX** [comment]
@Krot666 the commands should be working, can you please confirm if you managed to compile?

Compile the source from normal!

SovCoin
./autogen.sg
./configure
make


The commands to compile are working perfectly with  no issues!!

**Comment by Krot666** [comment]
Maybe I need a library?
How to check this point?
Although some errors and nothing is compiled (

**Comment by SovCoinX** [comment]
@Krot666 install all dependencies:

apt-get install git;apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils -y;apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev -y;apt-get install libboost-all-dev -y;apt-get install software-properties-common -y;add-apt-repository ppa:bitcoin/bitcoin -y;apt-get update;apt-get install libdb4.8-dev libdb4.8++-dev -y;apt-get install libminiupnpc-dev -y;apt-get install libzmq3-dev -y;apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler -y;apt-get install libqt4-dev libprotobuf-dev protobuf-compiler -y




Ubuntu 16.04

**Comment by Krot666** [comment]
![screenshot_1](https://user-images.githubusercontent.com/33595988/43071900-6712269e-8e9e-11e8-81ea-8123cfdc321a.png)
I have a version of Jesse.

**Comment by SovCoinX** [comment]
Try again we changed many lines should be resolved

**Comment by giaki3003** [comment]
As of update 1.3 only Gitian Builds will be supported, so we recommend building from Gitian. Thanks!
