### ISSUE TITLE
Virus scanner pegged the Windows binary as having a trojan.

### ISSUE THREAD

**Issue by pavulon18** [SovCoinX/SovCoin#4]
I downloaded the Windows Binary.  My virus scanner reported that it contained a Trojan.  Do you have any comments about this?

**Comment by sovgithub** [comment]
That would depend on the AV your using. I tested against Windows defender, malwarebytes,  and AVG.

**Comment by pavulon18** [comment]
360 Total Security (Free Edition) is the AV that is causing the positive notification.  I've tried to get a copy of the report but as of yet, I've not succeeded. I can try again if it will help you.

**Comment by sovgithub** [comment]
My only guess is because the wallet does have a builtin miner.

**Comment by pavulon18** [comment]
1) Could the miner you are using have a virus?

2) Why does it seem like so many files associated with cryptocurrencies and crypto mining have viruses?

I'm not trying to accuse you of anything.  I'm simply trying to figure out how to decide if crypto files in general are safe.

**Comment by sovgithub** [comment]
It's not a actual Virus as it's a false positive caused by people using miners in botnets which has made anti viruses flag them as viruses.

i understand your concern, I may look into removing the builtin miner down the road as GPU mining is far more efficient than the builtin cpuminer.

**Comment by pavulon18** [comment]
Thank you for that explanation.

So, for my own education, how does one go about determining if a miner is a false-positive (and thereby "safe") vs a miner that is truly infected?

**Comment by sovgithub** [comment]
Honestly it's all trial. I run all my wallets in a linux Jailshell environment so they only have access to minimal files. I only run miners on systems that have no Wallets on them to play it safe.

**Comment by pavulon18** [comment]
very nice solution.
